package com.yexh.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAccessToken<M extends BaseAccessToken<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	/**
	 * 用户 id
	 */
	public void setUid(java.lang.Long uid) {
		set("uid", uid);
	}
	
	/**
	 * 用户 id
	 */
	public java.lang.Long getUid() {
		return getLong("uid");
	}
	
	/**
	 * accesstoken
	 */
	public void setStoken(java.lang.String stoken) {
		set("stoken", stoken);
	}
	
	/**
	 * accesstoken
	 */
	public java.lang.String getStoken() {
		return getStr("stoken");
	}
	
	/**
	 * 到期时间戳
	 */
	public void setExpires(java.lang.Long expires) {
		set("expires", expires);
	}
	
	/**
	 * 到期时间戳
	 */
	public java.lang.Long getExpires() {
		return getLong("expires");
	}
	
	public void setCtime(java.lang.Long ctime) {
		set("ctime", ctime);
	}
	
	public java.lang.Long getCtime() {
		return getLong("ctime");
	}
	
}

