package com.yexh.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAccount<M extends BaseAccount<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	/**
	 * 手机号
	 */
	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}
	
	/**
	 * 手机号
	 */
	public java.lang.String getPhone() {
		return getStr("phone");
	}
	
	/**
	 * 积分
	 */
	public void setCredit(java.lang.Long credit) {
		set("credit", credit);
	}
	
	/**
	 * 积分
	 */
	public java.lang.Long getCredit() {
		return getLong("credit");
	}
	
	/**
	 * 运营商
	 */
	public void setOperator(java.lang.String operator) {
		set("operator", operator);
	}
	
	/**
	 * 运营商
	 */
	public java.lang.String getOperator() {
		return getStr("operator");
	}
	
	/**
	 * 创建时间
	 */
	public void setCtime(java.lang.Long ctime) {
		set("ctime", ctime);
	}
	
	/**
	 * 创建时间
	 */
	public java.lang.Long getCtime() {
		return getLong("ctime");
	}
	
}

