package com.yexh.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGame<M extends BaseGame<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}
	
	public void setIcon(java.lang.String icon) {
		set("icon", icon);
	}
	
	public java.lang.String getIcon() {
		return getStr("icon");
	}
	
	public void setSite(java.lang.String site) {
		set("site", site);
	}
	
	public java.lang.String getSite() {
		return getStr("site");
	}
	
	public void setPlatforms(java.lang.String platforms) {
		set("platforms", platforms);
	}
	
	public java.lang.String getPlatforms() {
		return getStr("platforms");
	}
	
	public void setPublisher(java.lang.String publisher) {
		set("publisher", publisher);
	}
	
	public java.lang.String getPublisher() {
		return getStr("publisher");
	}
	
	public void setDeveloper(java.lang.String developer) {
		set("developer", developer);
	}
	
	public java.lang.String getDeveloper() {
		return getStr("developer");
	}
	
	public void setTags(java.lang.String tags) {
		set("tags", tags);
	}
	
	public java.lang.String getTags() {
		return getStr("tags");
	}
	
	public void setArea(java.lang.String area) {
		set("area", area);
	}
	
	public java.lang.String getArea() {
		return getStr("area");
	}
	
	public void setPubdate(java.lang.Long pubdate) {
		set("pubdate", pubdate);
	}
	
	public java.lang.Long getPubdate() {
		return getLong("pubdate");
	}
	
	/**
	 * 是否已生成index, 未处理 0; 已处理 1; 无法处理 -1;
	 */
	public void setPstatus(java.lang.Integer pstatus) {
		set("pstatus", pstatus);
	}
	
	/**
	 * 是否已生成index, 未处理 0; 已处理 1; 无法处理 -1;
	 */
	public java.lang.Integer getPstatus() {
		return getInt("pstatus");
	}
	
	public void setImgUrl(java.lang.String imgUrl) {
		set("img_url", imgUrl);
	}
	
	public java.lang.String getImgUrl() {
		return getStr("img_url");
	}
	
}

