package com.yexh.model;

import com.yexh.model.base.BaseAccessToken;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AccessToken extends BaseAccessToken<AccessToken> {
	public static final AccessToken dao = new AccessToken().dao();
}

