package com.yexh.model;

import com.yexh.model.base.BaseGame;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Game extends BaseGame<Game> {
	public static final Game dao = new Game().dao();
}

